data:
  raw_path: data/raw/crop_recommendation.csv
  processed_dir: data/processed
  test_size: 0.2
  random_state: 42

model:
  n_estimators: 100
  max_depth: null
  random_state: 42

training:
  model_dir: models
  reports_dir: reports/figures

mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: crop-recommendation 